name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Run Tests with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20, 22, 24 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'

      - name: Install node modules
        run: |
          yarn install --immutable --check-cache

      - name: Run tests
        uses: willcaul/jest-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test"
  lint:
    name: Run Linter with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20, 22, 24 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'

      - name: Install node modules
        run: |
          yarn install --immutable --check-cache

      - name: Run ESLint
        run: |
          yarn lint --max-warnings=0

  import-checks:
    name: Run Import Checks with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20, 22, 24 ]
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'

      - name: Install node modules
        run: |
          yarn install --immutable --check-cache

      - name: Run import checks
        run: |
          yarn link
          cp -r gh-action-templates/import-check /tmp/import-check
          pushd /tmp/import-check
          yarn link simple-identicon
          node cjs/index.cjs
          node esm/index.mjs
          popd
